### ISSUE TITLE
DEP 5: less streaming

### ISSUE THREAD

**Issue by marfire** [django/deps#22]
I was confused by the use of the term *upstream* in this DEP:

> That is, when a middleware short-circuits the upstream middleware and view by returning a response, that response will only pass through previous middleware in the list.

and 

>  Similarly, a middleware that modifies the request on the way in and does pass it on upstream can be guaranteed that it will always see the response on the way back out.

If I'm reading this right, I would have used the term *downstream*. You process a request and pass it *downstream* to the next level, no?

Upon further reflection, a stream probably isn't a good metaphor for the bi-directional nature of middleware. *Higher* and *lower* might be clearer terms, given the presentation of middleware as a series of layers (e.g. the image in the documentation and the ordered list in settings).

**Comment by timgraham** [comment]
How about "when a middleware short-circuits the middleware that follow it and the view by..."

**Comment by carljm** [comment]
Yeah, I don't think there's a clear directionality to the upstream/downstream terminology in this case. I think of a request traveling "upstream" and then the response back "downstream," but that's probably just me :-) I pushed an update that removes use of those terms; let me know if you think it's still unclear. Thanks!

**Comment by marfire** [comment]
Looks good, but you forgot one: "Similarly, a middleware that modifies the request on the way in and does pass it on upstream...".

**Comment by carljm** [comment]
Huh, I thought I'd done a search, not sure how I missed that. Good catch, thanks; fixed.
